name: Sign and Verify

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 22.0

      - name: List directory
        run: ls -a

      - name: Install maven program
        run: mvn install

      - name: Print Successfull
        run: echo "SUCCESS"

      - name: Execute Main artifact
        run: mvn exec:java -Dexec.mainClass="ce.kiran.Main"
